---

- name: Copy logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/vault
    owner: root
    group: root
    mode: 0644

- name: Copy syslog config
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/vault.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_rsyslog

...
